### ISSUE TITLE
Could you please provide a Build guide for ESP32

### ISSUE THREAD

**Issue by abrilevskiy** [Ebiroll/esp32_sigrok#2]
Could you please provide a Build guide for ESP32

I just run make and received:
` make
Makefile:8: /make/project.mk: No such file or directory
make: *** No rule to make target '/make/project.mk'.  Stop.`

**Comment by Ebiroll** [comment]
It should be a standard ESP32 build.

Just set
export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
export IDF_PATH=~/esp/esp-idf
Follow instructions here,
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/
