### ISSUE TITLE
Could you please clarify how to connect PulseView and Analog mode

### ISSUE THREAD

**Issue by abrilevskiy** [Ebiroll/esp32_sigrok#3]
It is stated that analog mode should be used via: "sigrok-cli -d rigol-ds:conn=tcp-raw/192.168.1.130/5555  -l 5 --scan"
but it means that ESP32 should be connected via WiFi - based on source code it is not clear what Access point ESP32 create or which it tries to connect.

Thank you in advance!

**Comment by Ebiroll** [comment]
OK.
You must run make menuconfig

You must configure the ssid and password
https://github.com/Ebiroll/esp32_sigrok/blob/master/main/Kconfig.projbuild

**Comment by abrilevskiy** [comment]
Current Kconfig.projbuild specify ssid as "myssid" and password as "mypassword".
Is it a ESP32 access point configuration or it is configuration of access point that ESP32 will be connecting?

Thanks!
